### ISSUE TITLE
MultiTrove Getter Contract 

### ISSUE THREAD

**Issue by mccallofthewild** [notional-labs/UltraStableJuno#16]
CW Storage does a lot of heavy lifting here so this one may not be necessary either.

https://github.com/liquity/dev/blob/main/packages/contracts/contracts/MultiTroveGetter.sol

**Comment by chinhnotional** [comment]
Yes, I think this is unnecessary. After pushing the work to github and reporting the work progress tomorrow - July 22 or at the latest two weekends - July 23, 24/7 (if I'm late), we can close the PRs unnecessary.
